kind: ConfigMap
apiVersion: v1
metadata:
  name: litestream
  namespace: vrutkovs-dev
data:
  litestream.yaml: |
    dbs:
      - path: /gotosocial/data/sqlite.db
        replicas:
          - url: s3://vrutkovs-choomba/gotosocial-db
